### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by armengau**
Includes essentially:
- Fine-tuned some widgets layout, and finished to solve `#61` (reset x-range when changing spectrum)
- Solve `#44`: bug fixes in javascript, handling z_input / rest-frame issues.
- Several small bug fixes
- Large python code cleaning at various places:
    -  In particular, 'my*' functions are removed (not needed after desispec update https://github.com/desihub/desispec/issues/1298 ), 
    - Some functions in `utilities` are changed,
    - Related, all scripts are replaced by a single script `prospect_pages` (except for the pixel-based script).
- Doc: two notebooks updated, and a script `example_prospect_pages`, which can be used both as doc and tests.

Since there are already many changes, I'd like to merge this branch now, before Everest. I plan a much smaller PR just at the time of Everest, to fit changes in that data release - but I anticipated the structure.

Docs and tests are still to improve, however `example_prospect_pages` is already quite an improvement, can be used for tests (we need to inspect produced html pages anyway)

Questions:
- Since there's a new user interface, I guess this would deserve a new tag, maybe release 1.2.0 ? (I know I still have to update changes.rst before merging)
- I think we can remove plotframes.py + plotspecutils.py, do you agree ?
- I think we need to update specutils.py: this is essentially a copy of desispec.Spectra code, and prospect now relies on its new functionalities (slicing, select, ..). Do you agree ? In that case is it fine to just replace all of class Spectra + desispec.io.read/write_spectra according to the latest desispec ?

### CODE REVIEW

**Comment by armengau** [comment]
@weaverba137 I don't know if you are available for review now (it seems many in the US are on holiday now) - maybe Stephen can do it otherwise.
I made this PR now as I will be on leave the week around July 14.

**Comment by weaverba137** [comment]
I am on vacation, but I should have time to review early next week. I added @sbailey as a reviewer just in case.

**Comment by sbailey** [comment]
I don't have time to review this right now, but as a heads up we are finalizing tags for a 21.7 software release to go along with Everest.  @weaverba137 and @armengau if you can converge on this and make a tag this week, we could include the new prospect in the release.

**Comment by weaverba137** [comment]
@armengau, in the future, please make sure all tests are passing before requesting a review.

**Comment by weaverba137** [comment]
Before we can review, there's a serious problem in plotframes.py.  `prospect.utilities.match_vi_fames` no longer exists.  But plotframes.py *calls* `match_vi_frames()`:

```python
    vidata = match_vi_targets(vifile, spectra.fibermap['TARGETID'])
```
I don't know whether this line can simply be removed.

**Comment by armengau** [comment]
> Before we can review, there's a serious problem in plotframes.py. `prospect.utilities.match_vi_targets` no longer exists. But plotframes.py _calls_ `match_vi_targets()`:
> 
> ```python
>     vidata = match_vi_targets(vifile, spectra.fibermap['TARGETID'])
> ```
> 
> I don't know whether this line can simply be removed.



> Before we can review, there's a serious problem in plotframes.py. `prospect.utilities.match_vi_targets` no longer exists. But plotframes.py _calls_ `match_vi_targets()`:
> 
> ```python
>     vidata = match_vi_targets(vifile, spectra.fibermap['TARGETID'])
> ```
> 
> I don't know whether this line can simply be removed.

I think we can remove now both plotframes.py and plotspecutils.py , do you agree? They are both deprecated since (at least) the last PR several months ago.

**Comment by weaverba137** [comment]
That's fine, please go ahead and remove, but double-check that the `vidata` variable is not used.

**Comment by armengau** [comment]
I'm back from holiday.
Still to do, after the review is complete I guess: updated `changes.rst`, and possibly create a new tag.

**Comment by weaverba137** [comment]
Based on operational tests, this PR appears to be working.  Given the very large number of changes, perhaps we should simply merge and then create new issues and PRs after.  However:

> I think we need to update specutils.py: this is essentially a copy of desispec.Spectra code, and prospect now relies on its new functionalities (slicing, select, ..). Do you agree ? In that case is it fine to just replace all of class Spectra + desispec.io.read/write_spectra according to the latest desispec ?

specutils.py is emphatically *not* a copy of desispec.Spectra.  It is an *alternative* that loads DESI spectra into specutils objects.  These will have standard Numpy slicing capabilities.  I don't know about the "select" functionality, but that has to be tested.

**Comment by weaverba137** [comment]
Also, do we need to test this on everest, or will that be a separate issue/PR?

**Comment by sbailey** [comment]
Whether or not it is a separate ticket/PR, please do test this on Everest ASAP so that we can include a working prospect in a final software release to go along with Everest.

Two changes of note that could break prospect:
  * the underlying FIBERMAP table was split into quantities that can be meaningfully coadded (FIBERMAP) vs. ones that are per-exposure in a new EXP_FIBERMAP table.
  * zbest*.fits files with HDU "ZBEST" were renamed to redrock*.fits with HDU "REDSHIFTS"

If it is pragmatically necessary to break backwards compatibility, please make a final tag of improved prospect that works with Denali before moving on to changes to support Everest (and a new tag).  Thanks.

**Comment by armengau** [comment]
@weaverba137 
- OK for specutils, so the current version might actually work as it is, but anyway I don't think it's a show-stopper for this PR
- I plan to have a separate issue/PR for everest, as soon as this one is merged. Changes should be fast and limited (adapt scripts to healpix dirtree + new zbest filenames + adapt cds.py to fibermap changes). They should still be compatible with denali.

@sbailey What is the expected timescale for the software release?

**Comment by sbailey** [comment]
> @sbailey What is the expected timescale for the software release?

Thursday or Friday next week (July 29/30).

**Comment by armengau** [comment]
@weaverba137 @sbailey Finally given the limited amont of changes for everest + the timescale, I've just commited all everest-related changes now in the same branch.
All tests look ok on my side (at least for DESI data).

I've edited ``changes.rst``, but dont know which version name you want to give (maybe 1.2.0 given the changes in user scripts and functions). Except for this, for me it's ok to merge and include in everest software release.

**Comment by weaverba137** [comment]
Version 1.2.0 sounds good. Let's Hugo ahead and merge. Once Everest data are transferred to Tucson (in progress), I'll test there, but we can do separate issues/PRs for anything that comes up.

**Comment by weaverba137** [comment]
@armengau, there's no tag yet.  Are you waiting on me to create the tag?

**Comment by armengau** [comment]
@weaverba137 Yes I was actually thinking you would do it, I was not sure about whether to make a release or tag, and about release title and description. Can you do it?

**Comment by weaverba137** [comment]
Sure, I'll do that momentarily.

**Pull request merged**
