### PR TITLE
[WIP] Experimental support for plotting specutils-based spectra

### PR DESCRIPTION
**Pull request by weaverba137**
*This is a Work in Progress, do not merge yet.*

This PR adds experimental support for plotting specutils-based spectrum container objects, which is demonstrated by using the same code to plot both SDSS & DESI spectra.

Except for js/update_plot.js, this does not make any changes to the standard prospect API; all new code is self-contained in `prospect.plotspecutils`.

### CODE REVIEW

**Comment by armengau** [comment]
@weaverba137 for me can merge your branch whenever you want (I understand it's still work in progress). I started another branch scripts_n_doc from current master but I don't think there can be any interference (end-user scripts and improve doc)

**Comment by weaverba137** [comment]
@armengau , thank you.  I am still tracking down some bugs, so this is not ready to merge yet.

**Comment by weaverba137** [comment]
This is now ready for merge.  I know people are on vacation so this might not get a thorough review, but I'd like to merge soon.  Note that this PR addresses #45 and #46, though those should be examined and closed separately.

**Review by armengau — APPROVED** [review]
It looks all ok for me.

Just one question: is it ok to keep the console.log() commands in the code, or should they be commented at some point after debug?

**Comment by weaverba137** [comment]
Thank you for the reminder.  I will comment those out shortly, then we can proceed.

**Comment by weaverba137** [comment]
OK `console.log()` is commented  out.  @sbailey, please take a look before merging if you have a chance.

**Comment by weaverba137** [comment]
I want to do one more test before merging.  Should be ready to merge this afternoon.

**Comment by weaverba137** [comment]
OK, my tests look good, time to merge.

**Pull request merged**
